<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RestfulBooker.Core\RestfulBooker.Core.csproj" />
    <ProjectReference Include="..\RestfulBooker.Data\RestfulBooker.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Http\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="RestSharp" Version="114.0.0" />
  </ItemGroup>

</Project>
